### ISSUE TITLE
Namibia is missing

### ISSUE THREAD

**Issue by amreesh** [InternetHealthReport/as-hegemony#3]
Namibia (NA) is missing. It is probably because pandas consider the literal 'NA' as null values.

**Comment by romain-fontugne** [comment]
Thanks Amreesh. Indeed our code misinterpret NA as null values. I will try to fix that today.

**Comment by romain-fontugne** [comment]
OK, I could confirm the problem and fix the problem here: https://github.com/InternetHealthReport/country-as-hegemony/commit/2edfd14916c342a64211697107662825cd271c9d

Hopefully the rest of the pipeline will work as expected and we'll get Namibia results from tomorrow
